apiVersion: kp.kpack.io/v1alpha3
kind: DependencyDescriptor
defaultClusterBuilder: base
defaultClusterStack: base
lifecycle:
  image: registry.pivotal.io/tbs-dependencies/lifecycle@sha256:c923a81a1c3908122e29a30bae5886646d6ec26429bad4842c67103636041d93
clusterStores:
- name: default
  sources:
  - image: registry.pivotal.io/tanzu-go-buildpack/go@sha256:27b33492bfb9d8116b2689237161aecdaf7033a0f4b1e917481a70b58575ab2d
  - image: registry.pivotal.io/tanzu-java-buildpack/java@sha256:e7fd464a33a3c72c06874810719a03f88a3d45434c982ee9c0ae8f6434a53697
  - image: registry.pivotal.io/tanzu-nodejs-buildpack/nodejs@sha256:bc68b0d3c42eff1b9729c6a20fd22a1669a463c8adc4bbae2757972bcd5a6476
  - image: registry.pivotal.io/tanzu-java-native-image-buildpack/java-native-image@sha256:1470f053e4cc0d912d356f2299ae3fa195ab1baaabf1ce095cde184dab6759cc
  - image: registry.pivotal.io/tanzu-dotnet-core-buildpack/dotnet-core@sha256:6d57e312e7ac86f78ece4afcc3967e5314fbb71fe592800fd6f0f58bd923945a
  - image: registry.pivotal.io/tanzu-python-buildpack/python@sha256:1222d5f695222597687173b1b8612844f3ccd763eae86e99c3ebacc41390db40
  - image: registry.pivotal.io/tanzu-procfile-buildpack/procfile@sha256:0f34a11769a60568b7f1001f7bb99af6de50177aadd0241c486f59a1e90e0ee9
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_php@sha256:27f003c0ad6d45fd78cd9dbb71ae55b5ba1e599d8facfd98269dd29f42028870
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_nginx@sha256:5798dfecab8a4c67bbc3b956b6bef4474c52197b8949f02b8b866e19bfcde71e
  - image: registry.pivotal.io/tbs-dependencies/tanzu-buildpacks_httpd@sha256:4e15987d21d3d4f0cbc6be0d3b283db1d3f368eb15d0b1b59d835899c8bf946c
clusterStacks:
- name: tiny
  buildImage:
    image: registry.pivotal.io/tanzu-tiny-bionic-stack/build@sha256:d60adda2f6ea65ee7961de420607f4e363e280a017cc5f7c153352fc27f52759
  runImage:
    image: registry.pivotal.io/tanzu-tiny-bionic-stack/run@sha256:87d19b76688db4061e00ae6daa6f3e196c9b2900ae6766985c5385dd5ba55c7a
- name: base
  buildImage:
    image: registry.pivotal.io/tanzu-base-bionic-stack/build@sha256:db2e0eee786983ec26e25857a36b01281eada06ae1ff4cc1b2e27a579472937a
  runImage:
    image: registry.pivotal.io/tanzu-base-bionic-stack/run@sha256:7132773488dbcecdc0df19d7a677d7d6356bcabb17647e2589d1696735714c72
- name: full
  buildImage:
    image: registry.pivotal.io/tanzu-full-bionic-stack/build@sha256:5171011219934f52124a05faa730e8814181e6f67901bdc846ef1387a3acb869
  runImage:
    image: registry.pivotal.io/tanzu-full-bionic-stack/run@sha256:8137dbaa00e659b2a3998b8cec3553b1d2a5f247802284e33f152221462a916f
clusterBuilders:
- name: base
  clusterStack: base
  clusterStore: default
  order:
  - group:
    - id: tanzu-buildpacks/dotnet-core
  - group:
    - id: tanzu-buildpacks/nodejs
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/python
  - group:
    - id: tanzu-buildpacks/nginx
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: tanzu-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
- name: full
  clusterStack: full
  clusterStore: default
  order:
  - group:
    - id: tanzu-buildpacks/dotnet-core
  - group:
    - id: tanzu-buildpacks/nodejs
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/python
  - group:
    - id: tanzu-buildpacks/php
  - group:
    - id: tanzu-buildpacks/nginx
  - group:
    - id: tanzu-buildpacks/httpd
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: tanzu-buildpacks/java
  - group:
    - id: paketo-buildpacks/procfile
- name: tiny
  clusterStack: tiny
  clusterStore: default
  order:
  - group:
    - id: tanzu-buildpacks/go
  - group:
    - id: tanzu-buildpacks/java-native-image
  - group:
    - id: paketo-buildpacks/procfile
