apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vsan-rwm
provisioner: csi.vsphere.vmware.com
parameters:
  storagepolicyname: "VSAN Default Storage Policy"
  csi.storage.k8s.io/fstype: nfs4
