apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: pg-instance-example
spec:
  memory: 800Mi
  cpu: "0.8"
  storageClassName: tanzu
  monitorStorageClassName: tanzu
  storageSize: 500M
  pgConfig:
    dbname: pg-instance-example #Default: Same as Instance Name
    username: pgadmin
  serviceType: LoadBalancer #LoadBalancer or ClusterIP
  highAvailability:
    enabled: false #true: Deploy three pods, primary, standby, monitor. Only for 1 AZ
  backupLocationSecret:
    name:   #access Scret for S3
