---
apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
 name: tbs2
spec:
 distribution:
   version: v1.18.10
   #version: v1.16.8---vmware.1-tkg.3.60d2ffd
 topology:
   controlPlane:
     count: 3 #3 control plane nodes
     class: best-effort-small #2CPU, 2GB
     storageClass: tanzu #Specific storage class for control plane
     volumes:
       - name: etcd
         mountPath: /var/lib/etcd
         capacity:
           storage: 4Gi
   workers:
     count: 3 #5 worker nodes
     class: best-effort-medium #2CPU, 4GB
     storageClass: tanzu #Specific storage class for workers
     volumes:
       - name: containerd
         mountPath: /var/lib/containerd
         capacity:
           storage: 40Gi
 settings:
   storage:
     classes: ["tanzu"] #Named PVC storage classes
     defaultClass: tanzu #Default PVC storage class
   network:
     cni:
       name: antrea
     services:
       cidrBlocks: ["198.51.100.0/12"] #Cannot overlap with Supervisor Cluster
     pods:
       cidrBlocks: ["192.0.2.0/16"] #Cannot overlap with Supervisor Cluster
