---
apiVersion: v1
kind: Namespace
metadata:
  name: tkg-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  # Name must be `kapp-controller-config` for kapp controller to pick it up
  name: kapp-controller-config
  # Namespace must match the namespace kapp-controller is deployed to
  namespace: tkg-system
data:
  # A cert chain of trusted ca certs. These will be added to the system-wide
  # cert pool of trusted ca's (optional)
  caCerts: |
    -----BEGIN CERTIFICATE-----
    MIIDwTCCAqmgAwIBAgIQGqd0k74VRqNKSsmRf/CXBjANBgkqhkiG9w0BAQsFADBz
    MRIwEAYKCZImiZPyLGQBGRYCaW8xFzAVBgoJkiaJk/IsZAEZFgdwaXZvdGFsMRMw
    EQYKCZImiZPyLGQBGRYDcGV6MRQwEgYKCZImiZPyLGQBGRYEY2FhczEZMBcGA1UE
    AxMQY2Fhcy1DQUFTQURDMS1DQTAeFw0yMDA0MjMxOTIxNDNaFw0zMDA0MjMxOTMx
    NDJaMHMxEjAQBgoJkiaJk/IsZAEZFgJpbzEXMBUGCgmSJomT8ixkARkWB3Bpdm90
    YWwxEzARBgoJkiaJk/IsZAEZFgNwZXoxFDASBgoJkiaJk/IsZAEZFgRjYWFzMRkw
    FwYDVQQDExBjYWFzLUNBQVNBREMxLUNBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
    MIIBCgKCAQEAvdToshEoTJ2kV27tF4nyAnYoRNwAnnddVCGGl2xyZ37Wb3PITVmS
    0wqeqWqbXsD0JFpE/H1VqA9yCzaTkkRo4f5IN/SYlatdZExkIamXitkclh1TjfJk
    EBG0vKxxvl2FABCfnK/5A/Ev/MZn94dOg+jXqYISp0zMPnJFczca3IUIFuWcgJFg
    vVPPvh1P8aAFjfOFJYA743L24AdqzFqkCvRLikpGsOJufjyL7JuuAAK4kKeVX1dQ
    EjRuBtSa83zAt0a+0z3pzu+hAEsuyBdQXfT7wm1UEPI5iRkVmDDELdDGzM1l1O3c
    QmR+6gp6ef4qkyLszuUnoe6D4gS5ODWzRwIDAQABo1EwTzALBgNVHQ8EBAMCAYYw
    DwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUydOr0Ze4nCPq40ue9+IM5X04P84w
    EAYJKwYBBAGCNxUBBAMCAQAwDQYJKoZIhvcNAQELBQADggEBADSmfeC93Zzja6Iz
    dBEWoa4UgXEMDwYW7QXU9t9j0Gg77q4+C1MeGDmn1lZryybG5EC9x/0PGJjRS1Mo
    Gz6OC7KhHAQNuYg6uZE/twSR5l4ozGzGtmEjHoG0+qngBQtrxjYN/1j/YN2Nq+2Y
    ei64YddtsEuHgAlM3dUoKLJ7BuoB/ddl223vm4f4hZlr0zNjS1w0S5z8w9m5Q90C
    pSO+m8OB3/vWrSjh6y/8x8VgXI9fxLk0hdlykyyptFNI8fWh/yZWJ2lajpzEzQoT
    wzl1Tw32KwVurStEHkzH/7Iq1s2D718lHi4lqbXJ1j6TE+M1dayDlkdJuHMwXH3f
    28qq5Tg=
    -----END CERTIFICATE-----

  # The url/ip of a proxy for kapp controller to use when making network
  # requests (optional)
  httpProxy: ""

  # The url/ip of a tls capable proxy for kapp controller to use when
  # making network requests (optional)
  httpsProxy: ""

  # A comma delimited list of domain names which kapp controller should
  # bypass the proxy for when making requests (optional)
  noProxy: ""

  # A comma delimited list of hostnames for which kapp controller should
  # skip TLS verification (optional)
  dangerousSkipTLSVerify: ""
