---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "tanzu-mysql-operator.labels" . | nindent 4 }}
  name: {{ include "tanzu-mysql-operator.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tanzu-mysql-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tanzu-mysql-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "tanzu-mysql-operator.serviceAccountName" . }}
      containers:
      - args:
        - --enable-leader-election
        - --mysql-image={{ .Values.instanceImage }}
        - --metrics-addr=127.0.0.1:8080
        command:
        - /manager
        image: {{ .Values.operatorImage }}
        name: manager
        resources: {{ toYaml .Values.resources | nindent 10}}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      terminationGracePeriodSeconds: 10
