---
apiVersion: v1
kind: Service
metadata:
  name: win-webserver
  labels:
    app: win-webserver
spec:
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  selector:
    app: win-webserver
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: win-webserver
  name: win-webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: win-webserver
  template:
    metadata:
      labels:
        app: win-webserver
        name: win-webserver
    spec:
      containers:
      - name: windows-webserver
        image: harbor.tkgi.caas.pez.pivotal.io/windows/servercore:ltsc2019        
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: harbor
      tolerations:
      - key: "windows"
        operator: "Equal"
        value: "2019"
        effect: "NoSchedule"
      nodeSelector:
        beta.kubernetes.io/os: windows        