---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-tanzu-influxdb-storage-claim
spec:
  storageClassName: tanzu
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 5Gi
