imagePullSecret: harbor
operatorImage: "harbor.caas.pez.pivotal.io/tanzu-sql/tanzu-mysql-operator:1.0.0"
tanzuMySQLImage: "harbor.caas.pez.pivotal.io/tanzu-sql/tanzu-mysql-instance:1.0.0"
resources:
  limits:
    cpu: 100m
    memory: 30Mi
  requests:
    cpu: 100m
    memory: 20Mi
