operatorImageRepository: harbor.caas.pez.pivotal.io/tanzu-sql/postgres-operator
postgresImageRepository: harbor.caas.pez.pivotal.io/tanzu-sql/postgres-instance
dockerRegistrySecretName: harbor
certManagerClusterIssuerName: ca-issuer
