#@ load("/values.star", "values")
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  kp-config
  namespace: kpack
data:
  canonical.repository: #@ values.docker_repository
  canonical.repository.serviceaccount: canonical-registry-serviceaccount