---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: canonical-registry-serviceaccount
  namespace:  kpack
imagePullSecrets:
- name: canonical-registry-secret
secrets:
- name: canonical-registry-secret
