---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-test-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: vsan-rwm
  volumeMode: Filesystem
